include: https://gitlab-templates.ddbuild.io/compute-delivery/v3/compute-delivery.yml

build-docker-image:
  variables:
    EXTRA_ARGS: --file=dd.Dockerfile
    IMAGE_NAME: nvidia/kubevirt-gpu-device-plugin
  extends: .build-docker-image

build-merged-nydus-image:
  needs: ["build-docker-image"]
  variables:
    IMAGE_NAME: nvidia/kubevirt-gpu-device-plugin
    MERGE_PLATFORM: "true"
  extends: .build-nydus-image
