include: https://gitlab-templates.ddbuild.io/compute-delivery/v2/compute-delivery.yml

test:
  stage: verify
  tags: [ "arch:amd64" ]
  image: registry.ddbuild.io/images/mirror/golang:1.22
  variables:
    GOTOOLCHAIN: "auto"
  script:
    - make test

build-docker-image:
  variables:
    EXTRA_ARGS: --file=dd.Dockerfile
    IMAGE_NAME: nvidia/kubevirt-gpu-device-plugin
  extends: .build-docker-image
